---
title: "Lab 2"
author: "Your Name"
date: "4/7/2019"
output: html_document
---


#Lab Instructions

This lab is designed to give you practice acquiring data from an external site and reading it into R. In addition, it should give you more practice using R and Markdown, and provide experience using the R language when producing a

## Part 1: Data

* Find a data set you're interested in from Seattle's Open Data Portal at: https://data.seattle.gov/
* Download that dataset as a CSV file and save it to your computer.
* Write a code chunk to import the dataset into R using  read.csv().

## Part 2: Look at the data

Tell me something about the data you downloaded. Why do you think it's interesting? How large is it, what variables does it contain? What kind of information is available? What kind of questions might it let you answer? Use and display a few of the commands we've learned (table, head, dim, names) but try to make sure it displays in a readable way. Remember to create separate chunks of code like below and to discuss what you see in the output

```{r, echo=T}

```

## Part 3: Modifying data

If future weeks we'll learn about modifying data, how to change the orientation of a figure or remove some entries or many other things. Look at your data  and think about what would make the raw data more useful. Are dates entered in the wrong form? Do you need locations aggregated to a higher level? Are words entered inconsistently (i.e., Seattle, seattle, SEATTLE)? Start to think forward about what you want to learn to make data as useful as possible for you. If you are experienced with R, go ahead an modify one of the columns.

## Part 4: Final Project

* Look at the sources of life logging data you have available now. Make a list of the data sources you already have (already are signed up for).
* as a second (nested) point on each item, identify whether it is passive, active, or administrative data
* answer whether you can find a way to download the data you generate. If yes, post a link to where. If no, can you copy the information each day?

How many do you have, is there any type of data you lack, and is there anything else you're going to look into acquiring? Remember, you'll want to start data collection next week.



